# Generated by Django 4.2.20 on 2025-03-24 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.business'),
        ),
        migrations.AddField(
            model_name='item',
            name='bill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='billing.bill'),
        ),
        migrations.AddField(
            model_name='item',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.business'),
        ),
        migrations.AddField(
            model_name='bill',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.business'),
        ),
    ]
