# Generated by Django 4.2.20 on 2025-03-27 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_rename_item_billitem_bill_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('stripe', 'Stripe'), ('paypal', 'Paypal'), ('bank', 'Bank Transfer')], default='bank', max_length=20),
        ),
    ]
