# Generated by Django 4.2.20 on 2025-04-21 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_billparticipant'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='payment_mode',
            field=models.CharField(blank=True, choices=[('equal', 'Split Equally'), ('custom', 'Split Unequally'), ('items', 'Select Items')], max_length=10, null=True),
        ),
    ]
