# Generated by Django 4.2.20 on 2025-04-28 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0010_alter_bill_payment_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='participant_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
