# Generated by Django 4.2.20 on 2025-04-06 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_customuser_must_change_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('business_owner', 'Business Owner'), ('admin', 'Admin'), ('staff', 'Staff')], default='staff', max_length=20),
        ),
    ]
