# Generated by Django 4.2.20 on 2025-05-07 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0011_bill_participant_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnequalShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unequal_shares', to='billing.bill')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.billparticipant')),
            ],
            options={
                'unique_together': {('bill', 'participant')},
            },
        ),
    ]
